apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: ecosentinel
type: Opaque
stringData:
  DB_HOST: "database-service"
  DB_PORT: "5432"
  DB_NAME: "meter_anomaly"
  DB_USER: "postgres"
  DB_PASSWORD: "meter_pass"